# -*- coding: utf-8 -*-

# DO NOT EDIT THIS FILE!
# This file has been autogenerated by dephell <3
# https://github.com/dephell/dephell

try:
    from setuptools import setup
except ImportError:
    from distutils.core import setup

readme = ""

setup(
    long_description=readme,
    name="target_statistic_encoding",
    version="0.1.0",
    description="A lightweight library for encoding categorical features in your dataset with robust k-fold target statistics in training.",
    python_requires="==3.*,>=3.6.1",
    author="CircArgs",
    author_email="quebecname@gmail.com",
    license="MIT",
    packages=[],
    package_dir={"": "."},
    package_data={},
    install_requires=["pandas==0.*,>=0.23.0"],
    extras_require={
        "dev": [
            "black==19.*,>=19.10.0.b0",
            "dephell==0.*,>=0.8.3",
            "pylint==2.*,>=2.5.2",
            "pytest==3.*,>=3.0.0",
            "pytest-cov==2.*,>=2.4.0",
        ]
    },
)
